k2_se_ce_add_recipe("rubber")
k2_se_ce_add_recipe("potassium-nitrate")
k2_se_ce_add_recipe("gunpowder")
k2_se_ce_add_recipe("toluene")
k2_se_ce_add_recipe("drive-belt")
k2_se_ce_add_recipe("nitric-acid")
k2_se_ce_add_recipe("tnt")
k2_se_ce_add_recipe("gasket")
