k2_se_ce_add_recipe("helium")
k2_se_ce_add_recipe("filtered-oil")
k2_se_ce_add_recipe("empty-amplifier-tube")
k2_se_ce_add_recipe("helium-laser")
k2_se_ce_add_recipe("carbon-dioxide-laser")
k2_se_ce_add_recipe("scanner")
k2_se_ce_add_recipe("spectroscope")
--k2_se_ce_add_recipe("micron-tolerance-components")
k2_se_ce_add_recipe("laboratory-gear")
k2_se_ce_add_recipe("tracker")

