k2_se_ce_add_recipe("basic-electronic-components")
k2_se_ce_add_recipe("BOBMD-electronic-components")
k2_se_ce_add_recipe("integrated-electronics")
k2_se_ce_add_recipe("processing-electronics")
k2_se_ce_add_recipe("phenolic-board")
k2_se_ce_add_recipe("fibreglass-board")
k2_se_ce_add_recipe("basic-circuit-board")
k2_se_ce_add_recipe("circuit-board")
k2_se_ce_add_recipe("superior-circuit-board")
k2_se_ce_add_recipe("multi-layer-circuit-board")

