local parts = require("__ThemTharHills__/variable-parts")
k2_se_ce_add_recipe("gold-powder")
k2_se_ce_add_recipe(parts.gold)
k2_se_ce_add_recipe(parts.wire)
k2_se_ce_add_recipe("transceiver")
k2_se_ce_add_recipe("advanced-cable")
k2_se_ce_add_recipe("hv-power-regular")
k2_se_ce_add_recipe("integrated-circuit")
k2_se_ce_add_recipe("potassium-nitrate")
k2_se_ce_add_recipe("nitric-acid")
k2_se_ce_add_recipe("aqua-regia")
k2_se_ce_add_recipe("gold-ingot")
k2_se_ce_add_recipe("molten-gold")
